# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f018463aab326f901a8a7e1cf7369576bfc87469babdde30ed837bd2655614a07f566db9c6834a6f90eece869b173e5f0cef7227b7de543c0542dfb2eb31e67

test:
  secret_key_base: f9e693a03205bc0524b32d9bc6a4cf60bc79e9f8ea9eb24ac8f8ea5aaa6d9e7daa89c602b217074f0a61c0fef5e1e23a91c0084df5cf049fe6cd7b9fb94ec28b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
